# Setup
title:               Rishi Sareen
tagline:             ''
description:         'Triathlete. Reader. Following curiosity.'
url:                 https://rishisareen.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Rishi Sareen
  url:
  email:

# Gems
plugins:
  - jekyll-paginate

# Collections
collections:
  articles:
    output: true
    permalink: /articles/:title/
  notes:
    output: true
    permalink: /notes/:path/
  photography:
    output: true
    permalink: /photography/:title/

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
